# Generated by Django 3.1 on 2022-04-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_delete_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('isSignatureVerified', models.BooleanField()),
                ('isFaceVerified', models.BooleanField()),
            ],
        ),
    ]
